routes/web.php
<?php

use App\Http\Controllers\Admin\GenreController;
use App\Http\Controllers\Admin\MovieController;
use App\Http\Controllers\Controller;
use App\Http\Controllers\Movie\MovieDetailController;
use App\Http\Controllers\Movie\MovieListController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [Controller::class, 'home'])
    ->name('home');

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified',
])->group(function () {

    Route::prefix('admin')->name('admin.')->group(function () {
        Route::get('/dashboard', function () {
            return view('dashboard');
        })->name('dashboard');

        Route::resource('genres', GenreController::class);
        Route::resource('movies', MovieController::class);

    });

});

Route::get('/movies/day', [MovieListController::class, 'listDay'])
    ->name('movie-list-day');

Route::get('/movies/week', [MovieListController::class, 'listWeek'])
    ->name('movie-list-week');

Route::get('/movies/{id}', [MovieDetailController::class, 'detail'])
    ->name('movie-detail')
    ->where('id', '[0-9]+');

Route::permanentRedirect('/admin', '/admin/movies');
Route::permanentRedirect('/admin/dashboard', '/admin/movies');

app/Models/Movie.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Movie extends Model
{
    use HasFactory;

    protected $fillable = [
        'adult',
        'backdrop_path',
        'tmdb_id',
        'title',
        'original_language',
        'original_title',
        'overview',
        'poster_path',
        'popularity',
        'release_date',
        'vote_average',
        'vote_count',
        'refresh_trending_day_date',
        'refresh_trending_week_date'
    ];

    protected $casts = [
        'adult' => 'boolean',
        'budget' => 'integer',
        'tmdb_id' => 'integer',
        'release_date' => 'date',
        'id' => 'integer',
        'popularity' => 'float',
        'revenue' => 'integer',
        'vote_average' => 'float',
        'vote_count' => 'integer',
        'refresh_trending_day_date' => 'date',
        'refresh_trending_week_date' => 'date'
    ];

    public function genres()
    {
        return $this->belongsToMany(Genre::class);
    }

}

app/Http/Controllers/Admin/MovieController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Genre;
use App\Models\Movie;
use Illuminate\Http\Request;

class MovieController extends Controller
{

    public function index()
    {
        $movies = Movie::all();

        return view('admin.movie.index', compact('movies'));
    }

    public function show(Movie $movie)
    {
        return view('admin.movie.show', compact('movie'));
    }

    public function edit(Movie $movie)
    {

        $genres = Genre::all();

        return view('admin.movie.edit', compact('movie', 'genres'));
    }

    public function update(Request $request, Movie $movie)
    {

        $request->validate([
            'title' => 'required',
        ]);

        $movie->update($request->all());

        $movie->genres()->sync($request->input('genres'));

        return redirect()->route('admin.movies.index');
    }

    public function destroy(Movie $movie)
    {
        $movie->delete();

        return redirect()->route('admin.movies.index');
    }

}

app/Http/Controllers/Movie/MovieController.php
<?php

namespace App\Http\Controllers\Movie;

use App\Http\Controllers\Controller;
use App\Services\Genre\InitGenreService;
use App\Services\Genre\InitTrendingMovieService;
use App\Services\TMDB\TrendingMovieService;

abstract class MovieController extends Controller
{

    public function __construct(
        InitGenreService         $initGenreService,
        InitTrendingMovieService $initTrendingMovieService
    )
    {
        // Initialisation des genres dans l'application
        $initGenreService->createGenresFromApiIfNotExists();

        // Init/Rafraichissement des films trendings (1 fois par jour max)
        $initTrendingMovieService->refreshMoviesFromApi(TrendingMovieService::TIME_DAY);
        $initTrendingMovieService->refreshMoviesFromApi(TrendingMovieService::TIME_WEEK);
    }

}

app/Http/Controllers/Movie/MovieDetailController.php
<?php

namespace App\Http\Controllers\Movie;

use App\Models\Genre;
use App\Models\Movie;
use Illuminate\Contracts\View\View;

class MovieDetailController extends MovieController
{

    public function detail(int $id): View
    {
        $movie = Movie::find($id);

        if (!$movie) {
            abort(404, 'Movie non trouvé');
        }
        return view('movie.detail', ['movie' => $movie]);
    }

}

app/Http/Controllers/Movie/MovieListController.php
<?php

namespace App\Http\Controllers\Movie;

use App\Services\TMDB\TrendingMovieService;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class MovieListController extends MovieController
{

    public function listDay(Request $request): View
    {
        return view('movie.list', [
            'timeWindow' => TrendingMovieService::TIME_DAY,
            'search' => $request->input('search')
        ]);
    }


    public function listWeek(Request $request): View
    {
        return view('movie.list', [
            'timeWindow' => TrendingMovieService::TIME_WEEK,
            'search' => $request->input('search')
        ]);
    }

}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/admin/movie/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Editer un Film
        </h2>
    </x-slot>

    <div>
        <div class="max-w-4xl mx-auto py-10 sm:px-6 lg:px-8">

            <div class="mt-5 md:mt-0 md:col-span-2">
                <form method="post" action="{{ route('admin.movies.update', $movie->id) }}">
                    @csrf
                    @method('PUT')
                    <div class="shadow overflow-hidden sm:rounded-md">
                        <div class="px-4 py-5 bg-white sm:p-6">
                            <label for="name" class="required block font-medium text-sm text-gray-700">Title</label>
                            <input type="text" name="title" id="title" type="text" required="required"
                                   class="form-input rounded-md shadow-sm mt-1 block w-full"
                                   value="{{ old('title', $movie->title) }}" />
                            @error('title')
                            <p class="text-sm text-red-600">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="px-4 py-5 bg-white sm:p-6">
                            <label for="genres" class="block font-medium text-sm text-gray-700">Genres</label>
                            <select name="genres[]" id="genres" class="form-input rounded-md shadow-sm mt-1 block w-full" multiple>
                                @foreach ($genres as $genre)
                                    <option value="{{ $genre->id }}"
                                        {{ $movie->genres->contains($genre) ? 'selected' : '' }}>
                                        {{ $genre->name }}
                                    </option>
                                @endforeach
                            </select>
                        </div>

                        <div class="px-4 py-5 bg-white sm:p-6">
                            <label for="tmdb_id" class="block font-medium text-sm text-gray-700">tmdb_id</label>
                            <input disabled="disabled" type="text" name="tmdb_id" id="tmdb_id" type="text" class="form-input rounded-md shadow-sm mt-1 block w-full"
                                   value="{{ old('tmdb_id', $movie->tmdb_id) }}" />
                            @error('tmdb_id')
                            <p class="text-sm text-red-600">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="px-4 py-5 bg-white sm:p-6">
                            <label for="adult" class="block font-medium text-sm text-gray-700">Adult</label>
                            <input type="checkbox" name="adult" id="adult" class="form-checkbox h-5 w-5 text-indigo-600"
                                {{ $movie->adult ? 'checked' : '' }}>
                            @error('adult')
                            <p class="text-sm text-red-600">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="px-4 py-5 bg-white sm:p-6">
                            <label for="backdrop_path" class="block font-medium text-sm text-gray-700">Backdrop Path</label>
                            <input type="text" name="backdrop_path" id="backdrop_path" class="form-input rounded-md shadow-sm mt-1 block w-full"
                                   value="{{ old('backdrop_path', $movie->backdrop_path) }}" />
                            @error('backdrop_path')
                            <p class="text-sm text-red-600">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="px-4 py-5 bg-white sm:p-6">
                            <label for="original_language" class="block font-medium text-sm text-gray-700">Original Language</label>
                            <input type="text" name="original_language" id="original_language" class="form-input rounded-md shadow-sm mt-1 block w-full"
                                   value="{{ old('original_language', $movie->original_language) }}" />
                            @error('original_language')
                            <p class="text-sm text-red-600">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="px-4 py-5 bg-white sm:p-6">
                            <label for="original_title" class="block font-medium text-sm text-gray-700">Original Title</label>
                            <input type="text" name="original_title" id="original_title" class="form-input rounded-md shadow-sm mt-1 block w-full"
                                   value="{{ old('original_title', $movie->original_title) }}" />
                            @error('original_title')
                            <p class="text-sm text-red-600">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="px-4 py-5 bg-white sm:p-6">
                            <label for="overview" class="block font-medium text-sm text-gray-700">Overview</label>
                            <textarea name="overview" id="overview" class="form-input rounded-md shadow-sm mt-1 block w-full">{{ old('overview', $movie->overview) }}</textarea>
                            @error('overview')
                            <p class="text-sm text-red-600">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="px-4 py-5 bg-white sm:p-6">
                            <label for="poster_path" class="block font-medium text-sm text-gray-700">Poster Path</label>
                            <input type="text" name="poster_path" id="poster_path" class="form-input rounded-md shadow-sm mt-1 block w-full"
                                   value="{{ old('poster_path', $movie->poster_path) }}" />
                            @error('poster_path')
                            <p class="text-sm text-red-600">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="px-4 py-5 bg-white sm:p-6">
                            <label for="popularity" class="block font-medium text-sm text-gray-700">Popularity</label>
                            <input type="text" name="popularity" id="popularity" class="form-input rounded-md shadow-sm mt-1 block w-full"
                                   value="{{ old('popularity', $movie->popularity) }}" />
                            @error('popularity')
                            <p class="text-sm text-red-600">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="px-4 py-5 bg-white sm:p-6">
                            <label for="release_date" class="block font-medium text-sm text-gray-700">Release Date</label>
                            <input type="date" name="release_date" id="release_date" class="form-input rounded-md shadow-sm mt-1 block w-full"
                                   value="{{ old('release_date', $movie->release_date?->format('Y-m-d')) }}" />
                            @error('release_date')
                            <p class="text-sm text-red-600">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="px-4 py-5 bg-white sm:p-6">
                            <label for="vote_average" class="block font-medium text-sm text-gray-700">Vote Average</label>
                            <input type="text" name="vote_average" id="vote_average" class="form-input rounded-md shadow-sm mt-1 block w-full"
                                   value="{{ old('vote_average', $movie->vote_average) }}" disabled>
                            @error('vote_average')
                            <p class="text-sm text-red-600">{{ $message }}</p>
                            @enderror
                        </div>




                        <div class="px-4 py-5 bg-white sm:p-6">
                            <label for="vote_count" class="block font-medium text-sm text-gray-700">Vote Count</label>
                            <input disabled="disabled" type="number" name="vote_count" id="vote_count" class="form-input rounded-md shadow-sm mt-1 block w-full"
                                   value="{{ old('vote_count', $movie->vote_count) }}" />
                            @error('vote_count')
                            <p class="text-sm text-red-600">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="px-4 py-5 bg-white sm:p-6">
                            <label for="refresh_trending_day_date" class="block font-medium text-sm text-gray-700">Refresh Trending Day Date</label>
                            <input disabled="disabled" type="date" name="refresh_trending_day_date" id="refresh_trending_day_date" class="form-input rounded-md shadow-sm mt-1 block w-full"
                                   value="{{ old('refresh_trending_day_date', $movie->refresh_trending_day_date?->format('Y-m-d')) }}" />
                            @error('refresh_trending_day_date')
                            <p class="text-sm text-red-600">{{ $message }}</p>
                            @enderror
                        </div>

                        <div class="px-4 py-5 bg-white sm:p-6">
                            <label for="refresh_trending_week_date" class="block font-medium text-sm text-gray-700">Refresh Trending Week Date</label>
                            <input disabled="disabled" type="date" name="refresh_trending_week_date" id="refresh_trending_week_date" class="form-input rounded-md shadow-sm mt-1 block w-full"
                                   value="{{ old('refresh_trending_week_date', $movie->refresh_trending_week_date?->format('Y-m-d')) }}" />
                            @error('refresh_trending_week_date')
                            <p class="text-sm text-red-600">{{ $message }}</p>
                            @enderror
                        </div>



                        <div class="flex items-center justify-end px-4 py-3 bg-gray-50 text-right sm:px-6">
                            <button
                                class="inline-flex items-center px-4 py-2 bg-gray-800 border border-transparent rounded-md font-semibold text-xs text-white uppercase tracking-widest hover:bg-gray-700 active:bg-gray-900 focus:outline-none focus:border-gray-900 focus:shadow-outline-gray disabled:opacity-25 transition ease-in-out duration-150">
                                Editer
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/admin/movie/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Liste des Films
        </h2>
    </x-slot>

    <div>


        <div class="max-w-6xl mx-auto py-10 sm:px-6 lg:px-8">
            <div class="flex flex-col">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                    <div class="flex-auto block py-8 pt-6 px-9">
                        <div class="overflow-x-auto">
                            <table class="w-full my-0 align-middle text-dark border-neutral-200">
                                <thead class="align-bottom">
                                <tr class="font-semibold text-[0.95rem] text-secondary-dark">
                                    <th scope="col" class="pb-3 text-start">
                                        ID
                                    </th>
                                    <th scope="col" class="pb-3 text-start">
                                        Name
                                    </th>
                                    <th scope="col" class="pb-3 text-start">
                                        Date Last Trending Day Refresh
                                    </th>
                                    <th scope="col" class="pb-3 text-start">
                                        Date Last Trending Week Refresh
                                    </th>
                                    <th scope="col"  class="pb-3">

                                    </th>
                                </tr>
                                </thead>
                                <tbody class="bg-white divide-y divide-gray-200">
                                @foreach ($movies as $movie)
                                    <tr>
                                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                            {{ $movie->id }}
                                        </td>

                                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                            {{ $movie->title }}
                                        </td>

                                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                            {{ $movie->refresh_trending_day_date?->format('d-m-Y')}}
                                        </td>

                                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                            {{ $movie->refresh_trending_week_date?->format('d-m-Y')}}
                                        </td>

                                        <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                                            <a href="{{ route('admin.movies.show', $movie->id) }}" class="text-blue-600 hover:text-blue-900 mb-2 mr-2">Détail</a>
                                            <a href="{{ route('admin.movies.edit', $movie->id) }}" class="text-indigo-600 hover:text-indigo-900 mb-2 mr-2">Editer</a>
                                            <form class="inline-block" action="{{ route('admin.movies.destroy', $movie->id) }}" method="POST" onsubmit="return confirm('Etes-vous sûr ?');">
                                                <input type="hidden" name="_method" value="DELETE">
                                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                <input type="submit" class="text-red-600 hover:text-red-900 mb-2 mr-2" value="Supprimer">
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
</x-app-layout>

resources/views/admin/movie/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Détail Film
        </h2>
    </x-slot>

    <div>


        <div class="max-w-6xl mx-auto py-10 sm:px-6 lg:px-8">
            <div class="block mb-6">
                <a href="{{ route('admin.movies.index') }}" class="bg-gray-200 hover:bg-gray-300 text-black font-bold py-2 px-4 rounded">Retour à la liste</a>
            </div>

            <div class="flex flex-col">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                        <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                            <table class="min-w-full divide-y divide-gray-200 w-full">
                                <tr class="border-b">
                                    <th scope="col" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        ID
                                    </th>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 bg-white divide-y divide-gray-200">
                                        {{ $movie->id }}
                                    </td>
                                </tr>
                                <tr class="border-b">
                                    <th scope="col" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Name
                                    </th>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 bg-white divide-y divide-gray-200">
                                        {{ $movie->title }}
                                    </td>
                                </tr>
                                <tr class="border-b">
                                    <th scope="col" class="px-6 py-3 bg-gray-50 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        TMDB ID
                                    </th>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900 bg-white divide-y divide-gray-200">
                                        {{ $movie->tmdb_id }}
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="block mt-8">
                <a href="{{ route('admin.movies.index') }}" class="bg-gray-200 hover:bg-gray-300 text-black font-bold py-2 px-4 rounded">Retour à la liste</a>
            </div>
        </div>
    </div>
</x-app-layout>